# AI Code Scanner - regenerate scanner_versions.json from installed binaries.
# Runs version command on each tool, parses the output, writes a canonical
# manifest at the repo root.

$ErrorActionPreference = "Continue"
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

# Make Trivy reachable if PATH has not been picked up yet
if (-not (Get-Command trivy -ErrorAction SilentlyContinue)) {
    $env:Path += ";C:\Tools\trivy"
}

function Capture-Version {
    param([string]$Command, [string]$VersionFlag, [string]$Regex)
    try {
        $raw = & $Command $VersionFlag 2>&1 | Out-String
        if ($raw -match $Regex) {
            return $matches[1]
        }
    } catch {}
    return $null
}

$scanners = @{
    "semgrep" = @{
        version = Capture-Version "semgrep" "--version" '([\d\.]+)'
        language_coverage = @("all")
        categories = @("sast")
        rule_pack = "github.com/semgrep/semgrep-rules"
        install = "pip install semgrep"
        license = "LGPL-2.1"
        status = "active"
        phase_introduced = 2
    }
    "bandit" = @{
        version = Capture-Version "bandit" "--version" 'bandit\s+([\d\.]+)'
        language_coverage = @("python")
        categories = @("sast")
        install = "pip install bandit"
        license = "Apache-2.0"
        status = "installed"
        phase_introduced = 4
    }
    "safety" = @{
        version = Capture-Version "safety" "--version" 'safety,?\s+version\s+([\d\.]+)'
        language_coverage = @("python")
        categories = @("cve")
        install = "pip install safety"
        license = "MIT"
        status = "installed"
        phase_introduced = 4
    }
    "trufflehog" = @{
        version = $null
        language_coverage = @("all")
        categories = @("history", "secrets")
        install = "pip install trufflehog"
        license = "AGPL-3.0"
        status = "installed"
        phase_introduced = 4
    }
    "gitleaks" = @{
        version = Capture-Version "gitleaks" "version" '([\d\.]+)'
        language_coverage = @("all")
        categories = @("secrets")
        install = "Direct download from github.com/gitleaks/gitleaks"
        license = "MIT"
        status = "installed"
        phase_introduced = 3
    }
    "trivy" = @{
        version = Capture-Version "trivy" "--version" 'Version:\s+([\d\.]+)'
        language_coverage = @("all")
        categories = @("cve")
        install = "Direct download from github.com/aquasecurity/trivy"
        license = "Apache-2.0"
        status = "installed"
        phase_introduced = 3
    }
    "eslint-security" = @{
        version = Capture-Version "npx" "eslint --version" 'v?([\d\.]+)'
        language_coverage = @("javascript", "typescript")
        categories = @("sast")
        install = "npm install eslint eslint-plugin-security"
        license = "Apache-2.0"
        status = "installed"
        phase_introduced = 4
    }
    "gosec" = @{
        version = "dev"
        language_coverage = @("go")
        categories = @("sast")
        install = "go install github.com/securego/gosec/v2/cmd/gosec@latest"
        license = "Apache-2.0"
        status = "installed"
        phase_introduced = 4
    }
    "owasp-dep-check" = @{
        version = Capture-Version "dependency-check" "--version" 'version:?\s+([\d\.]+)'
        language_coverage = @("java")
        categories = @("cve")
        install = "Direct download from github.com/jeremylong/DependencyCheck"
        license = "Apache-2.0"
        status = "installed"
        phase_introduced = 4
    }
    "spotbugs" = @{
        version = Capture-Version "spotbugs" "-version" '([\d\.]+)'
        language_coverage = @("java")
        categories = @("sast")
        install = "Direct download from github.com/spotbugs/spotbugs"
        license = "LGPL-2.1"
        status = "installed"
        phase_introduced = 4
    }
}

$manifest = @{
    '$schema' = "https://json-schema.org/draft/2020-12/schema"
    description = "Pinned versions of every scanner integrated into the AI Code Scanner. Auto-generated by update-scanner-versions.ps1."
    generated_at = (Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ")
    scanners = $scanners
    host_runtime = @{
        python = ">=3.11"
        node = ">=20"
        go = ">=1.22"
        jdk = ">=17"
        docker_engine = ">=24.0"
        container_base_image = "python:3.11-slim-bookworm"
    }
}

$manifest | ConvertTo-Json -Depth 10 | Out-File -Encoding utf8 "$root\scanner_versions.json"

Write-Host ""
Write-Host "Scanner manifest written to scanner_versions.json:" -ForegroundColor Cyan
Write-Host ""
$scanners.GetEnumerator() | Sort-Object Key | ForEach-Object {
    $v = if ($_.Value.version) { $_.Value.version } else { "(unknown)" }
    Write-Host ("  {0,-20} {1}" -f $_.Key, $v)
}
Write-Host ""
