"""Detection rules for prompt_guard."""
from prompt_guard.rules.injection_rules import COMPILED_INJECTION_RULES, INJECTION_RULES
from prompt_guard.rules.jailbreak_rules import COMPILED_JAILBREAK_RULES, JAILBREAK_RULES
from prompt_guard.rules.exfiltration_rules import COMPILED_EXFILTRATION_RULES, EXFILTRATION_RULES
from prompt_guard.rules.roleplay_rules import COMPILED_ROLEPLAY_RULES, ROLEPLAY_RULES

ALL_RULES = (
    COMPILED_INJECTION_RULES
    + COMPILED_JAILBREAK_RULES
    + COMPILED_EXFILTRATION_RULES
    + COMPILED_ROLEPLAY_RULES
)

ALL_RAW_RULES = INJECTION_RULES + JAILBREAK_RULES + EXFILTRATION_RULES + ROLEPLAY_RULES

__all__ = [
    "COMPILED_INJECTION_RULES",
    "COMPILED_JAILBREAK_RULES",
    "COMPILED_EXFILTRATION_RULES",
    "COMPILED_ROLEPLAY_RULES",
    "ALL_RULES",
    "ALL_RAW_RULES",
]
